# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Prometheus
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: Prometheus
  type: prometheus
  uid: prometheus
  url: http://prometheus:9090
  jsonData:
    timeInterval: 60s
    exemplarTraceIdDestinations:
      - name: traceID
        datasourceUid: tempo
        urlDisplayLabel: 'Trace: $${__value.raw}'

- name: Tempo
  type: tempo
  uid: tempo
  url: http://localhost:3200
  jsonData:
    tracesToLogsV2:
      customQuery: true
      datasourceUid: 'loki'
      query: '{$${__tags}} | trace_id = "$${__trace.traceId}"'
      tags:
        - key: 'service.name'
          value: 'service_name'
      
    serviceMap:
      datasourceUid: prometheus
    search:
      hide: false
    nodeGraph:
      enabled: true
    lokiSearch:
      datasourceUid: 'loki'

- name: Loki
  type: loki
  uid: loki
  url: http://loki:3100
  jsonData:
    derivedFields:
      - datasourceUid: 'tempo'
        matcherType: 'label'
        matcherRegex: 'trace_id'
        name: 'trace_id'
        urlDisplayLabel: 'Trace: $${__value.raw}'
        url: '$${__value.raw}'