apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: namespace
  name: config-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: config-server
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: config-server
    spec:
      containers:
      - image: hyness/spring-cloud-config-server:latest
        name: config-server
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: awss3
        - name: SPRING_CLOUD_CONFIG_SERVER_AWSS3_REGION
          value: $AWSS3_REGION
        - name: SPRING_CLOUD_CONFIG_SERVER_AWSS3_BUCKET
          value: $AWSS3_BUCKET
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: /config-server
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-config
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-config
              key: AWS_SECRET_ACCESS_KEY
        ports:
        - containerPort: 8888
----
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: config-server
  namespace: namespace
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /config-server/actuator/health
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app.kubernetes.io/name: config-server
  type: ClusterIP
status:
  loadBalancer: {}
