version: '3.6'
services:
  redis-insight:
    image: "redislabs/redisinsight:latest"
    ports:
      - "8001:8001"
    volumes:
     - ~/.docker/redisinsight:/db
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_DEFAULT_PASS}
    ports:
      - "6379:6379"
    volumes:
     - ~/.docker/redis1/data:/data