receivers:
    otlp:
        protocols:
            grpc:
            http:
exporters:
    logging:
        loglevel: debug
    otlp/jaeger:
        endpoint: "jaeger-collector:4317"
processors:
    batch:
service:
    pipelines:
        traces:
            receivers: [otlp]
            exporters: [logging, otlp/jaeger]
            processors: []