receivers:
  otlp:
    protocols:
      grpc:      
processors:
  attributes:
    actions:
      - key: environment
        value: test
        action: insert
exporters:
  opencensus:
    endpoint: "jaeger-collector:14250"
    insecure: true

extensions:
  pprof:
    endpoint: :1777
  zpages:
    endpoint: :55679
  health_check:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes]
      exporters: [opencensus]
