global:
  scrape_interval: 1m

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "spring-actuator"
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
    - targets: ["localhost:8011"]