version: '3.7'

services:
    uptime-kuma:
        image: louislam/uptime-kuma:1
        container_name: uptime-kuma
        ports:
            - "3001:3001"
        volumes:
            - uptime-kuma:/app/data
        restart: always

volumes:
    uptime-kuma: