version: '3.8'

services:

  mongo:
    image: mongo@4.0.10
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DEFAULT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DEFAULT_PASS}
    volumes:
        - ~/.docker/mongodb/database:/data/db
    ports:
        - 27017:27017
    restart: unless-stopped

