  
version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
    volumes:
      - dataes:/usr/share/elasticsearch/data
    networks:
      - elasticsn
  kibana:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
    volumes:
      - dataki:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    networks:
      - elasticsn
volumes:
  dataes:
    driver: local
  dataki:
    driver: local

networks:
  elasticsn:
    driver: bridge