version: '3.7'

services:
    proxy:
        image: traefik:v2.4
        container_name: proxy
        # command: --providers.docker
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.yml:/traefik.yml
    nginx:
        image: nginx
        container_name: nginx
        labels:
            - "traefik.http.routers.nginx.rule=Host(`nginx.app.test`)"