receivers:
  otlp:
    protocols:
      grpc:
        # endpoint: 0.0.0.0:4317
      http:
        # endpoint: 0.0.0.0:4318
exporters:
  logging:
    # loglevel: debug
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/README.md
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp" #loki:3.1.1
    tls:
      insecure: true
processors:
    batch:
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp/loki]