
version: '3.7'
services:
  fluentd:
    image: grafana/fluent-plugin-loki:master
    command:
      - "fluentd"
      - "-v"
      - "-p"
      - "/fluentd/plugins"
    environment:
      LOKI_URL: http://loki:3100
      LOKI_USERNAME:
      LOKI_PASSWORD:
    container_name: "fluentd"
    #restart: always
    ports:
      - '24224:24224'
    networks:
      - yup-fluentd-net
    volumes:
      # - host_logs:/var/log
      # Needed for journald log ingestion:
      #- /etc/machine-id:/etc/machine-id
      #- /dev/log:/dev/log
      #- /var/run/systemd/journal/:/var/run/systemd/journal/      
      - type: bind
        source: ./fluentd/conf/fluent.conf
        target: /fluentd/etc/fluent.conf
      # - type: bind
      #   source: /var/lib/docker/containers
      #   target: /fluentd/log/containers
    logging:
      options:
        tag: docker.monitoring
      
  loki:
    image: grafana/loki:master
    container_name: "loki"
    # restart: always
    networks:
      - yup-fluentd-net
    ports:
      - 3100
    volumes:
      - type: bind
        source: ./loki/config/loki.conf
        target: /loki/etc/loki.conf
    depends_on:
      - fluentd

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
    networks:
      - yup-fluentd-net
  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: grafana-image-renderer
    expose:
      - "8081"
    environment:
      ENABLE_METRICS: "true"
    networks:
      - yup-fluentd-net
networks:
  yup-fluentd-net:
    external: true