version: '3.8'

networks:
    seqdevnetwork:

services:
    seqcli:
        image: datalust/seqcli:latest
        command: apikey create -t 'Logging.Net.Example' --token gNhQgRV8SKlVhkiaR8Oj -s http://seq
        depends_on:
          - seq
        restart: on-failure
        networks:
          - seqdevnetwork
        links:
          - seq
    seq:
        image: datalust/seq:latest
        environment:
            - ACCEPT_EULA=Y
        ports:
            - 80:80
            - 5341:5341
        networks:
            - seqdevnetwork