version: '3.3'

networks:
  network:
volumes:
  data:

services:
    seqcli:
        image: datalust/seqcli:latest
        command: apikey create -t 'Logging.Net.Example' --token gNhQgRV8SKlVhkiaR8Oj -s http://seq
        depends_on:
          - seq
        restart: on-failure
        networks:
          - network
        links:
          - seq
    seq:
        image: datalust/seq:latest
        volumes:
          - data:/data
        environment:
            - ACCEPT_EULA=Y
        ports:
            - 8080:80
            - 5341:5341
        networks:
            - network
        restart: always